### ISSUE TITLE
Audio frequency filter not working?

### ISSUE THREAD

**Issue by yvanlebras** [gibbona1/neal#6]
Trying to "zoom" on the frequency min and max of the spectrogram, it appears it is not working apparently trying to apply it using the "Audio Frequency Range:" slider. Is it the function of this slider? Is there something to do differently maybe ?

Thank you,

Yvan

**Comment by yvanlebras** [comment]
Update. After several tests, it seems modifying values on the slider change effectually the frequencies you are listening when playing the audio BUT the spectrogram is not updated thanks to these frequencies values

**Comment by gibbona1** [comment]
Thanks for catching this @yvanlebras! 
The three ways the audio is filtered is via drawing a box, zooming to a selection or using the frequency slider.
I added a little extra logic to first check if any box or zoom is done, and if so, continue to the spectrogram cropping regardless of whether the frequency slider check returns True. 
It should be fixed now but feel free to reopen if you see the issue again.
